spring.application.name=sb-ecom

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce_local}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ecomuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:localdevpassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

project.image=images/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.app.jwtSecret=${JWT_SECRET:mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm}
spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=springBootEcom

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG

# Needed if you are using elastic beanstalk
#server.port=5000

frontend.url=${FRONTEND_URL:http://localhost:5173/}
image.base.url=${IMAGE_BASE_URL:http://localhost:8080/images}

# STRIPE KEY
stripe.secret.key=${STRIPE_SECRET_KEY}

openai.api.key=${OPENAI_API_KEY}

# ===========================
# Redis
# ===========================
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# ===========================
# Spring Cache
# ===========================
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=sb-ecom: