spring.application.name=sb-ecom

spring.datasource.url=jdbc:postgresql://dpg-d8fv4h28qa3s73amekc0-a.frankfurt-postgres.render.com:5432/ecommerce_zg3o
spring.datasource.username=ecomuser
spring.datasource.password=xwMe5gZu7o4aVZBdJuArmrL7SvBASUVb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

project.image=images/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.app.jwtSecret=${JWT_SECRET:mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm}
spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=springBootEcom

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG

# Needed if you are using elastic beanstalk
#server.port=5000

frontend.url=${FRONTEND_URL:http://localhost:5173/}
image.base.url=${IMAGE_BASE_URL:http://localhost:8080/images}

# STRIPE KEY
stripe.secret.key=${STRIPE_SECRET_KEY}

openai.api.key=${OPENAI_API_KEY}


